base: &base

  # Training config
  weight_init: {conv_init: 'normal', conv_scale: 0.02, conv_bias: 0.}
  lr_schedule: {start_lr: 1.E-4, end_lr: 0., warmup_steps: 0}
  lambda_rho: 1E-2 # weight for additional rho loss term
  full_scale: True # whether or not to use all 6 of the scales in U-Net
  batch_size: 1
  num_epochs: 2
  enable_amp: False
  ngpu: 1
  expdir: '/global/cscratch1/sd/pharring/nbody2hydro/sc21/expts/'

  # Data
  data_loader_config: 'synthetic' # choices: 'synthetic', 'inmem', or 'lowmem'
  box_size: [1024, 1024] # total size of simulation boxes (train, validation) 
  data_size: 256 # size of crops for training
  num_data_workers: 2 # number of dataloader worker threads per proc
  N_out_channels: 5
  train_path: None
  val_path: None
  use_cache: None # set this to a cache dir (e.g., NVMe on CoriGPU) if you copied data there
  Nsamples: 20
  Nsamples_val: 20

withAMP:
  <<: *base
  enable_amp: True

multi8: 
  <<: *base
  ngpu: 8

cosmo: &cosmo
  <<: *base
  data_loader_config: 'lowmem'
  train_path: '/global/cscratch1/sd/pharring/nbody2hydro/datacopies/normalized1024_z3_alt_bigcrop_transp.h5'
  val_path: '/global/cscratch1/sd/pharring/nbody2hydro/datacopies/normalized1024_z3_alt_bigcrop2_transp.h5'
  use_cache: '/tmp/'
  Nsamples: 1000
  Nsamples_val: 64
  num_epochs: 20
  batch_size: 1 

cosmo_small: &cosmo_small
  <<: *base
  data_loader_config: 'lowmem'
  train_path: '/global/cscratch1/sd/pharring/nbody2hydro/datacopies/normalized1024_z3_alt_bigcrop_transp.h5'
  val_path: '/global/cscratch1/sd/pharring/nbody2hydro/datacopies/normalized1024_z3_alt_bigcrop2_transp.h5'
  use_cache: '/tmp/'
  data_size: 128
  Nsamples: 4096
  Nsamples_val: 256
  num_epochs: 20
  batch_size: 16


#------------------------------------------------------------------------

# A100 configs: for Perlmutter (crop sizes 64 and 96)
# Learning rates are pre-computed to obey the square-root scaling rule lr_Ngpu = sqrt(Ngpu)*lr_singlegpu

#------------------------------------------------------------------------

#                       ----   CROP SIZE 64   ----


A100_crop64_1GPU: &crop64_A100
  <<: *cosmo_small
  train_path: '/pscratch/sd/p/pharring/nbody2hydro/datacopies/downsamp_2048crop_train.h5'
  val_path: '/pscratch/sd/p/pharring/nbody2hydro/datacopies/downsamp_1024crop_valid.h5'
  expdir: '/pscratch/sd/p/pharring/nbody2hydro/sc21/expts/'
  box_size: [1024, 512]
  use_cache: None
  data_size: 64
  Nsamples: 4096
  Nsamples_val: 512
  num_epochs: 80
  batch_size: 64
  lr_schedule: {start_lr: 2.E-4, end_lr: 0., warmup_steps: 0}
  lambda_rho: 0.

A100_crop64_4GPU:
  <<: *crop64_A100
  lr_schedule: {start_lr: 4.E-4, end_lr: 0., warmup_steps: 128}
  ngpu: 4
  lambda_rho: 0.

A100_crop64_8GPU:
  <<: *crop64_A100
  lr_schedule: {start_lr: 5.66E-4, end_lr: 0., warmup_steps: 128}
  ngpu: 8
  lambda_rho: 0.

A100_crop64_32GPU:
  <<: *crop64_A100
  lr_schedule: {start_lr: 1.13E-3, end_lr: 0., warmup_steps: 128}
  ngpu: 32
  lambda_rho: 0.

A100_crop64_128GPU:
  <<: *crop64_A100
  lr_schedule: {start_lr: 2.26E-3, end_lr: 0., warmup_steps: 128}
  ngpu: 128
  lambda_rho: 0.



#                       ----   CROP SIZE 96   ----


A100_crop96_1GPU: &crop96_A100
  <<: *cosmo_small
  train_path: '/pscratch/sd/p/pharring/nbody2hydro/datacopies/downsamp_2048crop_train.h5'
  val_path: '/pscratch/sd/p/pharring/nbody2hydro/datacopies/downsamp_1024crop_valid.h5'
  expdir: '/pscratch/sd/p/pharring/nbody2hydro/sc21/expts/'
  box_size: [1024, 512]
  use_cache: None
  data_size: 96
  Nsamples: 4096
  Nsamples_val: 256
  num_epochs: 80
  full_scale: False
  batch_size: 64
  lr_schedule: {start_lr: 2.E-4, end_lr: 0., warmup_steps: 0}
  lambda_rho: 0.


A100_crop96_4GPU:
  <<: *crop96_A100
  lr_schedule: {start_lr: 4.E-4, end_lr: 0., warmup_steps: 128}
  ngpu: 4
  lambda_rho: 0.

A100_crop96_8GPU:
  <<: *crop96_A100
  lr_schedule: {start_lr: 5.66E-4, end_lr: 0., warmup_steps: 128}
  ngpu: 8
  lambda_rho: 0.

A100_crop96_32GPU:
  <<: *crop96_A100
  lr_schedule: {start_lr: 1.13E-3, end_lr: 0., warmup_steps: 128}
  ngpu: 32
  lambda_rho: 0.

A100_crop96_128GPU:
  <<: *crop96_A100
  lr_schedule: {start_lr: 2.26E-3, end_lr: 0., warmup_steps: 128}
  ngpu: 128
  lambda_rho: 0.

